Add cppzmq version 4.10.0.bcr.1 to fix build on Ubuntu Noble (#4556)
Build fails for version 4.10.0 on Ubuntu 24.04 (Noble) for depending
packages with
```
src/Discovery.cc:18:10: fatal error: zmq.hpp: No such file or directory
   18 | #include <zmq.hpp>
```

This is because the `cppzmq` target does not declare any `includes`. I
have added a new version `4.10.0.bcr.1` to address this issue.

Signed-off-by: Shameek Ganguly <shameek@intrinsic.ai>